[package]
name = "taffy"
version = "0.3.11"
authors = [
    "Alice Cecile <alice.i.cecile@gmail.com>",
    "Johnathan Kelley <jkelleyrtp@gmail.com>",
]
edition = "2021"
include = ["src/**/*", "Cargo.toml", "README.md"]
description = "A flexible UI layout library "
repository = "https://github.com/DioxusLabs/taffy"
keywords = ["cross-platform", "layout", "flexbox", "css-grid", "grid"]
categories = ["gui"]
license = "MIT"

[dependencies]
arrayvec = { version = "0.7", default-features = false }
num-traits = { version = "0.2", default-features = false }
rand = { version = "0.8.5", optional = true }
serde = { version = "1.0", optional = true, features = ["serde_derive"] }
slotmap = "1.0.6"
grid = { version = "0.9.0", optional = true }
once_cell = "1.18.0"
ordered-float = "3.4.0"
hashbrown = "0.14.0"

[features]
default = ["std", "flexbox", "grid"]
flexbox = []
grid = ["alloc", "dep:grid"]
alloc = []
std = ["num-traits/std"]
serde = ["dep:serde"]
random = ["dep:rand"]
yoga_benchmark = []
debug = []
profile = []

[dev-dependencies]
criterion = "0.4"
rstest = "0.17.0"
rand = "0.8.5"
rand_chacha = "0.3.1"
yoga = "0.4.0"
ordered-float = "3.4.0"
serde_json = "1.0.93"

# Enable example and test-specific features
taffy = { path = ".", features = ["random"] }

[profile.release]
lto = true
panic = 'abort'

[[bench]]
name = "tree_creation"
path = "benches/tree_creation.rs"
harness = false

[[bench]]
name = "flexbox"
path = "benches/flexbox.rs"
harness = false

[[bench]]
name = "grid"
path = "benches/grid.rs"
harness = false

[workspace]
members = ["scripts/gentest", "scripts/import-yoga-tests"]
